export const advisoryLabels: Record<string, string> = {
  decision_maker: 'Décideur',
  ai_referent: 'Référent IA interne',
  technical: 'Technique',
  business: 'Métier',
  other: 'Autre',
  low: 'Faible',
  medium: 'Moyen',
  high: 'Élevé',
  unknown: 'Non évalué',
  normal: 'Normale',
  critical: 'Critique',
  identified: 'Identifié',
  exploring: 'En exploration',
  addressed: 'Traité',
  dropped: 'Abandonné',
  meeting: 'Entretien',
  operator: 'Opérateur',
  client: 'Client',
  assist: 'Assister',
  automate: 'Automatiser',
  agent: 'Agent',
  analyze: 'Analyser',
  integrate: 'Intégrer',
  train: 'Former',
  idea: 'Idée',
  evaluating: 'En évaluation',
  proposed: 'Proposé',
  approved: 'Approuvé',
  rejected: 'Refusé',
  implemented: 'Mis en œuvre',
  accepted: 'Accepté',
  superseded: 'Remplacé',
  prototype: 'Prototype',
  integration: 'Intégration',
  automation: 'Automatisation',
  training: 'Formation',
  assessment: 'Évaluation',
  planned: 'Planifié',
  in_progress: 'En cours',
  delivered: 'Livré',
  paused: 'En pause',
  cancelled: 'Annulé',
  request: 'Demande',
  incident: 'Incident',
  intervention: 'Intervention',
  review: 'Revue',
  recommendation: 'Recommandation',
  open: 'Ouvert',
  awaiting_approval: 'À valider',
  completed: 'Terminé',
  workspace_membership: 'Membre du workspace',
  admin_api: 'API admin',
  oauth: 'OAuth',
  sso: 'SSO',
  manual: 'Manuel',
  active: 'Actif',
  pending: 'En attente',
  revoked: 'Révoqué',
  need_created: 'Besoin identifié',
  opportunity_created: 'Opportunité identifiée',
  decision_accepted: 'Décision acceptée',
  engagement_started: 'Réalisation démarrée',
  engagement_delivered: 'Réalisation livrée',
  action_completed: 'Action terminée',
}
export const advisoryLabel = (value: string) => advisoryLabels[value] ?? value
